# Generated by Django 2.2.6 on 2019-11-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='email_id',
            field=models.CharField(default='admin@gmail.com', max_length=100),
        ),
    ]
